api/urls.py
# from django.urls import path
from rest_framework.routers import DefaultRouter
from api.views import BookReviewsViewSet


app_name = 'api'

router = DefaultRouter()
router.register('reviews', BookReviewsViewSet, basename='review')


urlpatterns = router.urls

goodreads/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from .views import landing_page, home_page


urlpatterns = [
    path('', landing_page, name='landing_page'),
    path('home/', home_page, name='home_page'),
    path('users/', include('users.urls')),
    path('books/', include("books.urls")),
    path('api/', include('api.urls')),
    
    path('api-auth/', include('rest_framework.urls')),
    path('admin/', admin.site.urls),
]



# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import(
    RegisterView,
    LoginView,
    LogoutView,
    ProfileView,
    ProfileEditView,
)     



app_name = 'users'
urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', ProfileView.as_view(), name="profile"),
    path('profile/edit/', ProfileEditView.as_view(), name='profile-edit')
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):
    
    profile_picture = models.ImageField(default='default_profile_pic.jpeg')

users/forms.py
from typing import Any
from django import forms
from users.models import CustomUser


class UserCreateForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ('username', 'first_name', 'last_name', 'email', 'profile_picture', 'password')
    
    
    def save(self, commit=True):
        user = super().save(commit)
        user.set_password(self.cleaned_data['password'])
        user.save()
        
        return user




class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ('username', 'first_name', 'last_name', 'email', 'profile_picture')

users/views.py
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.views import View

from users.forms import UserCreateForm, UserUpdateForm




# Register
class RegisterView(View):
    
    def get(self, request):
        create_form = UserCreateForm()
        context = {'form': create_form}
        return render(request, 'users/register.html', context)
    
    
    def post(self, request):
        create_form = UserCreateForm(data=request.POST, files=request.FILES)
        
        if create_form.is_valid():
            create_form.save()
            return redirect('users:login')
        else:
            context = {'form': create_form}
            return render(request, 'users/register.html', context)
            




# Login
class LoginView(View):

    
    def get(self, request):
        login_form = AuthenticationForm()
        return render(request, 'users/login.html', {'login_form':login_form})
    
    
    
    def post(self, request):
        login_form = AuthenticationForm(data=request.POST)
        
        if login_form.is_valid():
            user = login_form.get_user()
            login(request, user)
            messages.success(request, "You have successfully logged in.")
            return redirect('books:list')
        else:
            return render(request, 'users/login.html', {'login_form':login_form})




# Logout
class LogoutView(LoginRequiredMixin, View):
    def get(self, request):
        logout(request)
        messages.info(request, "You have successfully logged out.")
        return redirect('landing_page')




# Profile
class ProfileView(LoginRequiredMixin, View):
    def get(self, request):
        return render(request, "users/profile.html", {"user": request.user})



# Profile Edit
class ProfileEditView(LoginRequiredMixin, View):
    
    def get(self, request):
        user_update_form = UserUpdateForm(instance=request.user)
        return render(request, 'users/profile_edit.html', {'form':user_update_form})
    
    
    def post(self, request):
        user_update_form = UserUpdateForm(instance=request.user, data=request.POST, files=request.FILES)
        
        if user_update_form.is_valid():
            user_update_form.save()
            messages.success(request, 'You have successfully updated your profile.')
            return redirect('users:profile')
        
        return render(request, 'users/profile_edit.html', {'form':user_update_form})

users/templates/users/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Log In{% endblock %}



{% block content %}

    <div class="container">

        <h3>Log in</h1>
        <div class="row">
            <div class="col-5">
                <form method="post" action="{% url 'users:login' %}">
                    {% csrf_token %}

                    {{ login_form|crispy }}
            
                    <button type="submit" class="btn btn-primary">Log in</button>
                </form>
                <br>
                    
                <div><a class="btn btn-outline-info" href="{% url 'users:register' %}">Register</a>  <span  style="text-decoration: underline;">If you don't have account. </span></div>
            </div>
        </div>

    </div>

{% endblock %}

users/templates/users/profile.html
{% extends 'base.html' %}
{% block title %}Profile{% endblock %}



{% block content %}



<div class="container mt-4 mb-4 p-3 d-flex justify-content-center">
    <div class="card p-4" style="width: 350px; background-color: #efefef; border: none; cursor: pointer; transition: all 0.5s;">
        <div class=" image d-flex flex-column justify-content-center align-items-center">
            <button class="btn btn-secondary">
                <img src="{{ user.profile_picture.url }}" height="100" width="100" alt="Profile picture" style="transition: all 0.5s; border-radius: 5px;"/>
            </button>
            <span class="name mt-3" style="font-size: 22px; font-weight: bold">{{ user.first_name }} {{ user.last_name }}</span>
            <span style="font-size: 14px; font-weight: 600">@{{ user.username }}</span>
            <div class="d-flex flex-row justify-content-center align-items-center gap-2"> 
                <span style="font-size: 14px; font-weight: 600">{{ user.email }}</span> 
                <span><i class="fa fa-copy"></i></span> 
            </div> 
            <div class=" d-flex mt-2"> <a href="{% url 'users:profile-edit' %}" class="btn btn-dark" role="button">Edit Profile</a> </div> 
            <div class="gap-3 mt-3 icons d-flex flex-row justify-content-center align-items-center"> 
                <!-- <span><i class="fa-brands fa-x-twitter"></i></span> <span><i class="fa-brands fa-facebook"></i></span> <span><i class="fa-brands fa-instagram"></i></span> <span><i class="fa-brands fa-linkedin"></i></span> -->
            </div> 
            <div class=" px-2 rounded mt-4 date "> 
                <span style="padding:4px; border-radius: 3px; background-color: #ccc; font-size: 14px; color: #828181; font-weight: bold">Joined:  <span style="color: #626161;">{{ user.date_joined | date:"M d, Y"}}</span></span> 
            </div> 
        </div> 
    </div>
</div>


{% endblock %}

users/templates/users/profile_edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}



{% block content %}

    <div class="container">


        <h3>Edit Profile</h3>


        <div class="rov">
            <div class="col-5">
                <form method="post" enctype="multipart/form-data">

                    {% csrf_token %}
                    {{ form|crispy }}

                    <button class="btn btn-success">Save</button>

                </form>
            </div>
        </div>


    </div>



    


{% endblock %}

users/templates/users/register.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Registration{% endblock %}



{% block content %}


    <div class="container">

        <h3>Register</h3>
        <div class="row">
            <div class="col-5">
                <form method="post" action="{% url 'users:register' %}">
                    {% csrf_token %}

                    {{ form|crispy }}
            
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
        </div>

    </div>
    
    


{% endblock %}