api/urls.py
# from django.urls import path
from rest_framework.routers import DefaultRouter
from api.views import BookReviewsViewSet


app_name = 'api'

router = DefaultRouter()
router.register('reviews', BookReviewsViewSet, basename='review')


urlpatterns = router.urls

books/urls.py
from django.urls import path
from books.views import BookView, BookDetailView, AddBookReview, EditReviewView, ConfirmDeleteReview, DeleteReviewView, CreateBookView


app_name = "books"
urlpatterns = [
    path("", BookView.as_view(), name='list'),
    path('create-book/', CreateBookView.as_view(), name='create-book'),
    path("<int:id>/", BookDetailView.as_view(), name="detail"),
    path("<int:id>/reviews/", AddBookReview.as_view(), name='reviews'),
    path("<int:book_id>/review/<int:review_id>/edit/", EditReviewView.as_view(), name='edit-review'),
    path("<int:book_id>/review/<int:review_id>/delete/confirm/", ConfirmDeleteReview.as_view(), name='confirm-delete-review'),
    path("<int:book_id>/review/<int:review_id>/delete/", DeleteReviewView.as_view(), name='delete-review'),
]

goodreads/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from .views import landing_page, home_page


urlpatterns = [
    path('', landing_page, name='landing_page'),
    path('home/', home_page, name='home_page'),
    path('users/', include('users.urls')),
    path('books/', include("books.urls")),
    path('api/', include('api.urls')),
    
    path('api-auth/', include('rest_framework.urls')),
    path('admin/', admin.site.urls),
]



# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import(
    RegisterView,
    LoginView,
    LogoutView,
    ProfileView,
    ProfileEditView,
)     



app_name = 'users'
urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', ProfileView.as_view(), name="profile"),
    path('profile/edit/', ProfileEditView.as_view(), name='profile-edit')
]

templates/base.html
{% load static %}
{% url 'landing_page' as landing_page_url %}
{% url 'home_page' as home_page_url %}
{% url 'books:list' as books_page_url %}
{% url 'users:profile' as profile_page_url %}
{% url 'books:create-book' as create_book_url %}



<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Goodreads Clone{% endblock %}</title>
    <link rel="stylesheet" type="test/css" href="{% static 'css/main.css' %}">

    <!--CSS BOOTSTRAP-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">
    <!--CSS BOOTSTRAP-->


    <!-- CSS -->
    <style>
        @media(min-width:568px){
            .end{
                margin-left: auto;
            }
        }
        
        @media(max-width:768px){
            #post{
                width: 100%;
            }
        }      
        
        #post{
            margin: 10px;
            padding: 6px;
            padding-top: 2px;
            padding-bottom: 2px;
            text-align: center;
            background-color: rgb(109, 181, 2);
            border: none;
            color: rgb(250, 248, 248);
            border-radius: 13px;
            width: 50%;
        }   
        
        #nav-items li a,#profile{
            text-decoration: none;
            color: rgb(224, 219, 219);
            background-color: black;
        }
        
        .comments{
            background-color: azure;
            margin-top: 5%;
            margin-left: 20px;
        }
        
        .darker{
            background-color: black;
            float: right;
            border-radius: 5px;
            padding-left: 40px;
            padding-right: 30px;
            padding-top: 10px;
        }
        
        .comment{
            background-color: rgba(139, 181, 160, 0.973);
            float: left;
            border-radius: 5px;
            padding-left: 40px;
            padding-right: 30px;
            padding-top: 10px;
            
        }
        .comment h4,.comment span,.darker h4,.darker span{
            display: inline;
        }
        
        .comment p,.comment span,.darker p,.darker span{
            color: rgb(3, 3, 3);
        }
        
        
        .com-label{
            color: rgb(7, 7, 7);
        }
        
        #align-form{
            margin-top: 20px;
        }
        .form-group p a{
            color: white;
        }
        
        #checkbx{
            background-color: black;
        }
        
        #darker img{
            margin-right: 15px;
            position: static;
        }
        
        .form-group input,.form-group textarea{
            background-color: rgb(252, 251, 251);
            border-radius: 12px;
        }
        
        .com-form{
            background-color: rgba(231, 230, 230, 0.973);
            border-radius: 5px;
            padding: 20px;
         }
    </style>
    <!-- CSS -->
    
</head>
<body class="pb-3">


<!--NAVBAR SECTION-->

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-5 sticky-top">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'landing_page' %}">Goodreads Clone</a>
      
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
      
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link {% if request.path == home_page_url %} active {% endif %}" aria-current="page" href="{{ home_page_url }}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link {% if request.path == books_page_url %} active {% endif %}" aria-current="page" href="{{ books_page_url }}">Books</a>
              </li>
            </ul>
      
            <div class="me-5">
                {% if request.user.is_authenticated %}
                    <ul class="navbar-nav">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle {% if request.path == profile_page_url or request.path == profile_edit_page_url %} active {% endif %}" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                {{ request.user.username }}
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                              <li><a class="dropdown-item" href="{{profile_page_url}}">Profile</a></li>
                              <li><hr class="dropdown-divider"></li>
                              <li><a class="dropdown-item" href="{{create_book_url}}">Create Book</a></li>
                              <li><hr class="dropdown-divider"></li>
                              <li><a class="dropdown-item" href="{% url 'users:logout' %}">Log out</a></li>
                            </ul>
                        </li>
                    </ul>
                {% else %}
                    <a class="btn btn-outline-info" href="{% url 'users:login' %}">Login</a>
                {% endif %}
            </div>
          </div>
        </div>
      </nav>
    
<!--NAVBAR SECTION-->




    <div class="container">

        {% if messages %}
            <div class="mt-2">
                {% for message in messages %}
                    <span class=""></span>
                    <div class="alert alert-{{ message.tags }}" role="alert">
                        {{ message }}
                    </div>
                {% endfor %}  
            </div>  
        {% endif %}






        <!-- block -->
        {% block content %}
        {% endblock %}
        <!-- block -->

    </div>

   




<!--JS BOOTSTRAP-->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
<!--JS BOOTSTRAP-->
<script src="https://kit.fontawesome.com/a076d05399.js"></script>
  

</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}






{% block content %}

<h3 style="margin: 0 0 0 10px;">All reviews</h3>

{% for review in page_obj %}
  <div class="container mt-5">
    <div class="card" style="width: 600px;">
        <div class="card-header" >
          <div class="d-flex align-items-center">
            <img src="{{ review.user.profile_picture.url }}" class="rounded-circle me-3" width="40" height="40" alt="Profile Picture">
            <p style="font-size: 18px; font-weight: 500;" class="mb-0">{{ review.user.username }}</p>
          </div>
        </div>

        <div style="width: 100%; background-color:rgb(216, 216, 217)">
          <img src="{{ review.book.cover_picture.url }}" style="width: 300px; margin:10px 10px;" alt="Post Image">
        </div>

        <div class="card-body p-2" style="background-color: #F7F7F7;">
            <p class="mt-1">
                <strong>john_doe</strong>: {{ review.comment | truncatechars:300 }}
            </p>
            <div style="font-size: 16px; color:grey; margin:0 0 10px 5px">At: {{ review.created_at | date:'M, d, Y' }}</div>
        </div>
    </div>
  </div>
{% endfor %}



<nav style="margin: 50px 0 0 0;">

  <ul class="pagination justify-content-center">
      {% if page_obj.has_previous %}
          <li class="page-item"><a class="page-link bg-dark text-light" href="?page=1">&laquo; first</a></li>
          <li class="page-item"><a class="page-link bg-dark text-light" href="?page={{ page_obj.previous_page_number }}">previous</a></li>
      {% endif %}

          <li class="page-item active" aria-current="page"><a href="#" class="page-link bg-dark">{{ page_obj.number }}</a></li>

      {% if page_obj.has_next %}
          <li class="page-item"><a class="page-link bg-dark text-light" href="?page={{ page_obj.next_page_number }}">Next</a></li>
          <li class="page-item"><a class="page-link bg-dark text-light" href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a></li>
      {% endif %}
  </ul>

</nav>






{% endblock %}

templates/landing.html
{% extends 'base.html' %}


{% block content %}
    <h3>Landing Page</h3>
    <div style="font-weight: bold; ">When I was in second grade, I discovered the Hardy Boys series. Ever since, I've loved to read — both for fun and to improve my mind. And I'm always looking for the next great book.

        One afternoon while I was scanning a friend's bookshelf for ideas, it struck me: when I want to know what books to read, I'd rather turn to a friend than any random person or bestseller list.
        
        So I decided to build a website – a place where I could see my friends' bookshelves and learn about what they thought of all their books. Elizabeth, my co-founder (and now my wife) wrote the site copy and I wrote the code. We started in my living room, motivated by the belief that there was a better way to discover and discuss good books, and that we could build it.</div>
{% endblock %}