api/urls.py
# from django.urls import path
from rest_framework.routers import DefaultRouter
from api.views import BookReviewsViewSet


app_name = 'api'

router = DefaultRouter()
router.register('reviews', BookReviewsViewSet, basename='review')


urlpatterns = router.urls

books/urls.py
from django.urls import path
from books.views import BookView, BookDetailView, AddBookReview, EditReviewView, ConfirmDeleteReview, DeleteReviewView, CreateBookView


app_name = "books"
urlpatterns = [
    path("", BookView.as_view(), name='list'),
    path('create-book/', CreateBookView.as_view(), name='create-book'),
    path("<int:id>/", BookDetailView.as_view(), name="detail"),
    path("<int:id>/reviews/", AddBookReview.as_view(), name='reviews'),
    path("<int:book_id>/review/<int:review_id>/edit/", EditReviewView.as_view(), name='edit-review'),
    path("<int:book_id>/review/<int:review_id>/delete/confirm/", ConfirmDeleteReview.as_view(), name='confirm-delete-review'),
    path("<int:book_id>/review/<int:review_id>/delete/", DeleteReviewView.as_view(), name='delete-review'),
]

goodreads/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from .views import landing_page, home_page


urlpatterns = [
    path('', landing_page, name='landing_page'),
    path('home/', home_page, name='home_page'),
    path('users/', include('users.urls')),
    path('books/', include("books.urls")),
    path('api/', include('api.urls')),
    
    path('api-auth/', include('rest_framework.urls')),
    path('admin/', admin.site.urls),
]



# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

books/models.py
from django.db import models
from users.models import CustomUser
from django.core.validators import MinValueValidator, MaxValueValidator
from django.utils import timezone

class Book(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    isbn = models.CharField(max_length=17)
    cover_picture = models.ImageField(default='default_cover.jpeg')
    
    def __str__(self):
        return self.title



class Author(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField()
    bio = models.TextField()
    
    def __str__(self):
        return f"{self.first_name} {self.last_name}"


    def full_name(self):
        return f'{self.first_name} {self.last_name}'



class BookAuthor(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    
    def __str__(self):
        return f"{self.book.title} by {self.author}"

    
    

class BookReview(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    comment = models.TextField()
    created_at = models.DateTimeField(default=timezone.now)
    stars_given = models.IntegerField(
        validators=[MinValueValidator(1), MaxValueValidator(5)]
    )

books/forms.py
from django import forms
from books.models import BookReview, Book



class BookReviewForm(forms.ModelForm):
    stars_given = forms.IntegerField(min_value=1, max_value=5)
    
    class Meta:
        model = BookReview
        fields = ('comment', 'stars_given')


class CreateBookForm(forms.ModelForm):
    isbn = forms.CharField(max_length=17)
    
    class Meta:
        model = Book
        fields = ('title', 'description', 'isbn', 'cover_picture')

books/views.py
from django.shortcuts import redirect, render
from django.urls import reverse
from django.views import View
from django.contrib import messages
from django.core.paginator import Paginator
from django.views.generic import ListView, DetailView, CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from books.models import Book, BookReview
from books.forms import BookReviewForm, CreateBookForm




# class BookView(ListView):
#     template_name = 'books/list.html'
#     queryset = Book.objects.all()
#     context_object_name = "books"
#     paginate_by = 2


class BookView(View):
    def get(self, request):
        books = Book.objects.all().order_by('id')
        search_query = request.GET.get('q', '')
        if search_query:
            books = books.filter(title__icontains=search_query)
        
        page_size = request.GET.get('page_size', 6)
        paginator = Paginator(books, page_size)
        
        page_num = request.GET.get('page', 1)
        page_obj = paginator.get_page(page_num)
        
        
        return render(request, 'books/list.html', {"page_obj": page_obj, "search_query": search_query})







# class BookDetailView(DetailView):
#     template_name = 'books/book_detail.html'
#     pk_url_kwarg = 'id'
#     model = Book
#     context_object_name = 'book'
    


class BookDetailView(View):
    def get(self, request, id): 
        book = Book.objects.get(id=id)
        review_form = BookReviewForm()
        
        
        return render(request, "books/book_detail.html", {"book": book, "review_form": review_form})




class AddBookReview(LoginRequiredMixin, View):
    def post(self, request, id):
        book = Book.objects.get(id=id)
        review_form = BookReviewForm(data=request.POST)
        
        if review_form.is_valid():
            BookReview.objects.create(
                book = book,
                user = request.user,
                stars_given = review_form.cleaned_data['stars_given'],
                comment = review_form.cleaned_data['comment']
            )
            
            return redirect(reverse('books:detail', kwargs={"id":book.id}))
        
        return render(request, 'books/book_detail.html', {"book":book, "review_form":review_form})







# edit review class
class EditReviewView(LoginRequiredMixin, View):
    def get(self, request, book_id, review_id):
        book = Book.objects.get(id=book_id)
        review = book.bookreview_set.get(id=review_id)
        review_form = BookReviewForm(instance=review)
        
        return render(request, 'books/edit_review.html', {'book':book, 'review':review, 'review_form':review_form})
    
    
    def post(self, request, book_id, review_id):
        book = Book.objects.get(id=book_id)
        review = book.bookreview_set.get(id=review_id)
        review_form = BookReviewForm(instance=review, data=request.POST)
        
        if review_form.is_valid():
            review_form.save()
            return redirect(reverse('books:detail', kwargs={"id":book.id}))
        
        return render(request, 'books/edit_review.html', {'book':book, 'review':review, 'review_form':review_form})





class ConfirmDeleteReview(LoginRequiredMixin, View):
    def get(self, request, book_id, review_id):
        book = Book.objects.get(id=book_id)
        review = book.bookreview_set.get(id=review_id)
        return render(request, 'books/confirm_delete_review.html', {'book':book, 'review':review})





class DeleteReviewView(LoginRequiredMixin, View):
    def get(self, request, book_id, review_id):
        book = Book.objects.get(id=book_id)
        review = book.bookreview_set.get(id=review_id)
        
        review.delete()
        messages .success(request, 'You have successfly deleted this review')
        return redirect(reverse('books:detail', kwargs={"id":book.id}))








class CreateBookView(View):
    
    def get(self, request):
        create_book_form = CreateBookForm()
        
        return render(request, 'books/create_book.html', {'create_book': create_book_form})
    
    
    
    def post(self, request):
        create_book_form = CreateBookForm(data=request.POST, files=request.FILES)
        
        if create_book_form.is_valid():
            create_book_form.save()
            messages.success(request, "You have successfully created book.")
            return redirect('books:list')

        return render(request, 'books/create_book.html', {'create_book': create_book_form})
            

books/templates/books/book_detail.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Book Detail{% endblock %}



{% block content %}
    <div class="container">


        <!-- book -->
        <div class="row row-cols-auto">
            <div class="col" style="max-width: 210px;">
                <img class="img-fluid rounded-end" src="{{ book.cover_picture.url }}">
            </div>

            <div class="col-8">
                <h3 class="lib-row lib-header">{{ book.title }}</h3>
                <div style="font-size: 18px; font-weight:bold">Author by:
                    {% for book_author in book.bookauthor_set.all %}
                        {% if forloop.last %}
                            <i>{{ book_author.author.full_name }}</i>
                        {% else %}
                            <i>{{ book_author.author.full_name }},</i>
                        {% endif %}
                    {% endfor %}
                </div>
                <br>
                <div class="lib-row lib-desc">
                    {{ book.description }}
                </div>   
            </div>
        </div>
        <br><br><br><br><br><br>
        <!-- book -->




        
            <!-- reviews start-->
            <section>
                <div class="container">
                    <div class="row">

                        <h3 style="color: black; font-weight: bold;">Reviews</h3><hr>
                        {% if book.bookreview_set.exists %}
                        <div class="col-sm-5 col-md-6 col-12 pb-4 d-flex flex-column">
                            {% for review in book.bookreview_set.all %}
                                <div class="col comment mt-4 text-justify float-left pb-3">
                                    <img src="{{ review.user.profile_picture.url }}" alt="" class="rounded-circle" width="40" height="40">
                                    <span style="font-size: 18px; font-weight:bold; margin: 0px 0 0 10px">{{ review.user.username }}</span>
                                    <span>- rated it {{ review.stars_given }} <span style="color: yellow;"><i class="bi bi-star-fill"></i></span> </span>
                                    <br>
                                    <p class="mt-3 font-monospace">{{ review.comment }}</p>
                                    <div style="color: rgb(108, 107, 107); padding:0 0 15px 0;">{{ review.created_at }}</div>
                                    
                                    {% if review.user == request.user %}
                                    <div class="mt-3">
                                        <a href="{% url 'books:edit-review' book.id review.id  %}" role="button" class="btn btn-success"><i class="bi bi-pen"></i></a>
                                        <a href="{% url 'books:confirm-delete-review' book.id review.id  %}" role="button" class="btn btn-danger"><i class="bi bi-trash3"></i></a>
                                    </div>
                                    {% endif %}
                                </div>     
                            {% endfor %}
                        </div>
                        {% endif %}





                        <div class="col-lg-4 col-md-5 col-sm-4 offset-md-1 offset-sm-1 col-12 mt-4">
                            <form class="com-form" id="algin-form" method="post" action="{% url 'books:reviews' book.id %}">

                                {% csrf_token %}
                                {{ review_form | crispy }}

                                <button class="btn btn-success my-3">Post Comment</button>

                            </form>
                        </div>

                    </div>
                </div>
            </section>
            <!-- reviews end -->
        





    </div>
{% endblock %}

books/templates/books/confirm_delete_review.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Edit Review{% endblock %}


{% block content %}

<h3 style="color: red;">Delete review</h3>
<br>

<div> 
    <h5 style="background-color: red; padding: 10px; border-radius: 5px; color: white; width:fit-content">Are you sure, you want to delete this comment</h5>
    <br>

    <p> <b> Book:</b> {{ book.title }}</p>
    <p> <b> Comment:</b> {{ review.comment }}</p>
    <br>
    <a href="{% url 'books:delete-review' book.id review.id %}" class="btn btn-outline-danger"><i class="bi bi-trash3"></i> Yes</a>
    <a href="{% url 'books:detail' book.id %}" class="btn btn-outline-primary"><i class="bi bi-arrow-counterclockwise"></i> No</a>

</div>

{% endblock  %}

books/templates/books/create_book.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Book Detail{% endblock %}



{% block content %}
    <h3 clas>Create Book</h3>
    <br><br><br><br>

    <div class="col-lg-4 col-md-5 col-sm-4 offset-md-1 offset-sm-1 col-12 mt-4">
        <form class="com-form" id="algin-form" method="post" action="{% url 'books:create-book' %}" enctype="multipart/form-data">

            {% csrf_token %}
            {{ create_book | crispy }}

            <button class="btn btn-success my-3">Create</button>

        </form>
    </div>

{% endblock %}

books/templates/books/edit_review.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Edit Review{% endblock %}



{% block content %}
<h3>Edit Review</h3>
<br><br>



<div class="col-lg-4 col-md-5 col-sm-2">
    <form class="com-form" method="post" action="{% url 'books:edit-review' book.id review.id  %}">

        {% csrf_token %}
        {{ review_form | crispy }}

        <button class="btn btn-success my-3">Edit Comment</button>

    </form>
</div>


{% endblock %}

books/templates/books/list.html
{% extends 'base.html' %}
{% block title %}Books List{% endblock %}





{% block content %}

    <h3>Books</h3>
    
        <div class="mb-3" style="max-width: 400px; min-width: 200px">
            <form class="d-flex" method="get">
                <input width="400px" class="form-control me-2" type="text" placeholder="Search" name="q" value="{{ search_query }}">

                <button class="btn btn-success">Search</button>
            </form>
        </div>

    {% if page_obj %}
        
            {% for book in page_obj.object_list %}
            
                    <div class="row row-cols-auto">
                        <div class="col" style="max-width: 190px;">
                            <img src="{{ book.cover_picture.url }}" class="img-fluid rounded-end" alt="book cover picture">
                        </div>
                        <div class="col-7">
                            <div class="card-body pt-1 ps-0">
                                <h5 class="card-title"><a style="color: black;" href="{% url 'books:detail' book.id %}">{{ book.title }}</a></h5>
                                <p class="card-text">{{ book.description|truncatewords:40}}</p>
                            </div>
                        </div>
                    </div>
                <hr>
            
            {% endfor %}
            


            <nav>

                <ul class="pagination justify-content-center">
                    {% if page_obj.has_previous %}
                        <li class="page-item"><a class="page-link bg-dark text-light" href="?page=1">&laquo; first</a></li>
                        <li class="page-item"><a class="page-link bg-dark text-light" href="?page={{ page_obj.previous_page_number }}">previous</a></li>
                    {% endif %}

                        <li class="page-item active" aria-current="page"><a href="#" class="page-link bg-dark">{{ page_obj.number }}</a></li>

                    {% if page_obj.has_next %}
                        <li class="page-item"><a class="page-link bg-dark text-light" href="?page={{ page_obj.next_page_number }}">Next</a></li>
                        <li class="page-item"><a class="page-link bg-dark text-light" href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a></li>
                    {% endif %}
                </ul>

            </nav>





    {% else %}
        No books found.
    {% endif %}


{% endblock %}